project:
  type: website
  output-dir: docs

website:
  title: "Santa Cruz Monarch Movement Dashboard"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: detections.qmd
        text: Detection Explorer

      - href: detections_by_tag.qmd
        text: Detections by Tag

      - href: episodes.qmd
        text: Episode Explorer

      - href: episodes_by_tag.qmd
        text: Episodes by Tag

render:
  - "*.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    