---
title: "Episode Explorer"
---

```{r}
#| echo: false
#| warning: false
#| message: false

library(sf)
library(leaflet)

boundary102 <- readRDS(
  "data/boundary102.rds"
)

episode_lines <- readRDS(
  "data/episode_lines.rds"
)

boundary102 <-
  boundary102[
    boundary102$SiteName %in%
      unique(
        na.omit(
          c(
            episode_lines$departed_site,
            episode_lines$arrived_site
          )
        )
      ),
  ]

behavior_pal <- c(
  migration = "#E69F00",
  premigration = "#0072B2",
  winter = "#009E73"
)
```

Interactive map of movement episodes.

```{r}
#| echo: false

leaflet() |>

  addProviderTiles(
    providers$Esri.WorldTopoMap
  ) |>

  addPolygons(
    data = boundary102,

    fillColor =
      ~ifelse(
        SiteStatus == "Active",
        "#1B9E77",
        "#BDBDBD"
      ),

    fillOpacity = 0.3,

    color = "black",

    weight = 1
  ) |>

  addPolylines(
    data = episode_lines,

    color =
      ~behavior_pal[
        behavior_type
      ],

    weight = 2,

    opacity = 0.8,

    popup =
      ~paste0(
        "<b>Tag:</b> ",
        tag_id,

        "<br><b>Tracking:</b> ",
        tracking_period,

        "<br><b>Behavior:</b> ",
        behavior_type,

        "<br><b>Episode Type:</b> ",
        episode_type,

        "<br><b>Duration (min):</b> ",
        round(duration_min),

        "<br><b>Departed:</b> ",
        departed_site,

        "<br><b>Arrived:</b> ",
        arrived_site
      )
  )
```